name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install git make wget gcc libevent-dev libcsfml-dev file g++ cpio unzip rsync bc bzip2 libcairo-dev
          ./build.sh goke
          ./build.sh hisi
          ./build.sh star6b0
          ./build.sh star6e
          ./build.sh native
          ./build.sh rockchip

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          path: |
              msposd_goke
              msposd_hisi
              msposd_star6b0
              msposd_star6e
              msposd
              msposd_rockchip

      - name: Versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.3.1
        with:
          files: |
            msposd_goke
            msposd_hisi
            msposd_star6b0
            msposd_star6e
            msposd
            msposd_rockchip

      - name: Upload latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v2.3.1
        with:
          tag_name: latest
          files: |
            msposd_goke
            msposd_hisi
            msposd_star6b0
            msposd_star6e
            msposd
            msposd_rockchip
